// Generated by https://quicktype.io

export interface Asset {
  id:           string;
  barcode:      string;
  serialNumber: string;
  latitude:     string;
  longitude:    string;
  province:     string;
  town:         string;
  floor:        string;
  roomNumber:   number;
  group:        Category;
  category:     Category;
  componen:     Componen;
  type:         Category;
  subcategory:  Category;
  condition:    Category;
  createdBy:    By;
  updateBy:     By;
  createdDate:  string;
  updateDate:   string;
  client:       Client;
  description:  string;
  custodian:    string;
  attachment:   null;
}

export interface Category {
  id:   string;
  name: string;
}

export interface Client {
  id:            string;
  name:          string;
  contactNumber: string;
  location:      string;
  email:         string;
  town:          string;
  province:      string;
}

export interface Componen {
  id:          string;
  name:        string;
  description: null;
}

export interface By {
  id:             string;
  createDate:     null;
  firstName:      string;
  lastName:       string;
  idNumber:       null;
  contactNumber:  null;
  employeeNumber: null;
  password:       null;
  email:          null;
  roles:          null;
}
